### ISSUE TITLE
undefined method `rails_metrics'

### ISSUE THREAD

**Issue by levifig** [engineyard/rails_metrics#1]
After installing rails_metrics on my app, when I run "rails g rails_metrics Metric" this is what I get:

<pre>
DEPRECATION WARNING: railtie_name is deprecated and has no effect. (called from <class:Engine> at /*****/.rvm/gems/ruby-1.9.2-head/bundler/gems/rails_metrics-9fc009a4f0aaaf533f1dd284dd9961b905e5b8db-master/lib/rails_metrics/engine.rb:3)
/*****/.rvm/gems/ruby-1.9.2-head/gems/railties-3.0.0.beta2/lib/rails/railtie/configuration.rb:59:in `method_missing': undefined method `rails_metrics' for #<Rails::Engine::Configuration:0x00000100cd1ad0> (NoMethodError)
    from /*****/.rvm/gems/ruby-1.9.2-head/bundler/gems/rails_metrics-9fc009a4f0aaaf533f1dd284dd9961b905e5b8db-master/lib/rails_metrics/engine.rb:6:in `<class:Engine>'
    from /*****/.rvm/gems/ruby-1.9.2-head/bundler/gems/rails_metrics-9fc009a4f0aaaf533f1dd284dd9961b905e5b8db-master/lib/rails_metrics/engine.rb:2:in `<module:RailsMetrics>'
    from /*****/.rvm/gems/ruby-1.9.2-head/bundler/gems/rails_metrics-9fc009a4f0aaaf533f1dd284dd9961b905e5b8db-master/lib/rails_metrics/engine.rb:1:in `<top (required)>'
    from /*****/.rvm/gems/ruby-1.9.2-head/bundler/gems/rails_metrics-9fc009a4f0aaaf533f1dd284dd9961b905e5b8db-master/lib/rails_metrics.rb:112:in `require'
    from /*****/.rvm/gems/ruby-1.9.2-head/bundler/gems/rails_metrics-9fc009a4f0aaaf533f1dd284dd9961b905e5b8db-master/lib/rails_metrics.rb:112:in `<top (required)>'
    from /*****/.rvm/gems/ruby-1.9.2-head/gems/bundler-0.9.16/lib/bundler/runtime.rb:45:in `require'
    from /*****/.rvm/gems/ruby-1.9.2-head/gems/bundler-0.9.16/lib/bundler/runtime.rb:45:in `block (2 levels) in require'
    from /*****/.rvm/gems/ruby-1.9.2-head/gems/bundler-0.9.16/lib/bundler/runtime.rb:40:in `each'
    from /*****/.rvm/gems/ruby-1.9.2-head/gems/bundler-0.9.16/lib/bundler/runtime.rb:40:in `block in require'
    from /*****/.rvm/gems/ruby-1.9.2-head/gems/bundler-0.9.16/lib/bundler/runtime.rb:39:in `each'
    from /*****/.rvm/gems/ruby-1.9.2-head/gems/bundler-0.9.16/lib/bundler/runtime.rb:39:in `require'
    from /*****/.rvm/gems/ruby-1.9.2-head/gems/bundler-0.9.16/lib/bundler.rb:73:in `require'
    from /*****/Workspace/CODENAMED/nancyapp/config/application.rb:7:in `<top (required)>'
    from /*****/Workspace/CODENAMED/nancyapp/config/environment.rb:2:in `require'
    from /*****/Workspace/CODENAMED/nancyapp/config/environment.rb:2:in `<top (required)>'
    from /*****/.rvm/gems/ruby-1.9.2-head/gems/railties-3.0.0.beta2/lib/rails/commands.rb:29:in `require'
    from /*****/.rvm/gems/ruby-1.9.2-head/gems/railties-3.0.0.beta2/lib/rails/commands.rb:29:in `<top (required)>'
    from script/rails:9:in `require'
    from script/rails:9:in `<main>'
</pre>

Running it on 3.0.0.beta2 and Ruby 1.9.2-head, via RVM btw… :)

Cheers,
~Levi Figueira

**Comment by splattael** [comment]
It works in master has been probably fixed in 2535b2be9bb2d79b80261e77bbbdeb8184143c82.

**Comment by seanlinsley** [comment]
Indeed this works on master.
