### ISSUE TITLE
undefined method `middleware' 

### ISSUE THREAD

**Issue by o-sam-o** [engineyard/rails_metrics#3]
ska:swarm sam$ rails g rails_metrics Metric
DEPRECATION WARNING: railtie_name is deprecated and has no effect. (called from <top (required)> at /Users/sam/Programming/ruby/swarm/config/application.rb:7)
/Users/sam/.rvm/gems/ruby-1.9.2-p0@sw/gems/railties-3.0.0/lib/rails/railtie/configuration.rb:76:in `method_missing': undefined method`middleware' for #Rails::Engine::Configuration:0x000001015dd958 (NoMethodError)
        from /Users/sam/.rvm/gems/ruby-1.9.2-p0@sw/gems/rails_metrics-0.1/lib/rails_metrics/engine.rb:6:in `<class:Engine>'
        from /Users/sam/.rvm/gems/ruby-1.9.2-p0@sw/gems/rails_metrics-0.1/lib/rails_metrics/engine.rb:2:in`module:RailsMetrics'
        from /Users/sam/.rvm/gems/ruby-1.9.2-p0@sw/gems/rails_metrics-0.1/lib/rails_metrics/engine.rb:1:in `<top (required)>'
        from /Users/sam/.rvm/gems/ruby-1.9.2-p0@sw/gems/rails_metrics-0.1/lib/rails_metrics.rb:112:in`require'
        from /Users/sam/.rvm/gems/ruby-1.9.2-p0@sw/gems/rails_metrics-0.1/lib/rails_metrics.rb:112:in `<top (required)>'
        from /Users/sam/.rvm/gems/ruby-1.9.2-p0@sw/gems/bundler-1.0.0.rc.6/lib/bundler/runtime.rb:64:in`require'
        from /Users/sam/.rvm/gems/ruby-1.9.2-p0@sw/gems/bundler-1.0.0.rc.6/lib/bundler/runtime.rb:64:in `block (2 levels) in require'
        from /Users/sam/.rvm/gems/ruby-1.9.2-p0@sw/gems/bundler-1.0.0.rc.6/lib/bundler/runtime.rb:62:in`each'
        from /Users/sam/.rvm/gems/ruby-1.9.2-p0@sw/gems/bundler-1.0.0.rc.6/lib/bundler/runtime.rb:62:in `block in require'
        from /Users/sam/.rvm/gems/ruby-1.9.2-p0@sw/gems/bundler-1.0.0.rc.6/lib/bundler/runtime.rb:51:in`each'
        from /Users/sam/.rvm/gems/ruby-1.9.2-p0@sw/gems/bundler-1.0.0.rc.6/lib/bundler/runtime.rb:51:in `require'
        from /Users/sam/.rvm/gems/ruby-1.9.2-p0@sw/gems/bundler-1.0.0.rc.6/lib/bundler.rb:112:in`require'
        from /Users/sam/Programming/ruby/swarm/config/application.rb:7:in `<top (required)>'
        from /Users/sam/.rvm/gems/ruby-1.9.2-p0@sw/gems/railties-3.0.0/lib/rails/commands.rb:15:in`require'
        from /Users/sam/.rvm/gems/ruby-1.9.2-p0@sw/gems/railties-3.0.0/lib/rails/commands.rb:15:in `<top (required)>'
        from script/rails:6:in`require'

**Comment by o-sam-o** [comment]
Fixed here: http://github.com/milann/rails_metrics

**Comment by splattael** [comment]
It works in master and has been fixed in: 552e811af45a771f9c6376439539fa0addcc1f53
